package com.example.helloworldjfxtemplate.DAO;

import java.sql.ResultSet;
import java.sql.Statement;

import static com.example.helloworldjfxtemplate.helper.JDBC.connection;

/**
 * Handles the DAO implementation for generic Querying of the database.
 * This code was provided by the Course Instructor Team Resources.
 */
public class Query {
    private static String query;
    private static Statement stmt;
    private static ResultSet result;

    /**
     * Executes a CRUD operation based on the query String.
     * @param q The query String which should be an SQL statement.
     */
    public static void makeQuery(String q){
        query =q;
        try{
            stmt=connection.createStatement();
            // determine query execution
            if(query.toLowerCase().startsWith("select"))
                result=stmt.executeQuery(q);
            if(query.toLowerCase().startsWith("delete")||query.toLowerCase().startsWith("insert")||query.toLowerCase().startsWith("update"))
                stmt.executeUpdate(q);

        }
        catch(Exception ex){
            System.out.println("Error: "+ex.getMessage());
        }
    }

    /**
     * Returns the ResultSet generated by the Query.
     * @return The result of the Query.
     */
    public static ResultSet getResult(){
        return result;
    }
}